[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  REACT_APP_BACKEND_URL = "https://backend-yauo.onrender.com"
     CI = "false"
     
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200